### ISSUE TITLE
Feedback on Part 1

### ISSUE THREAD

**Issue by TanSA05** [adastra21/ttc_streetcar_delays#1]
Your business case is clear. I see the raw data is loaded, but it hasn’t been cleaned yet. Roles and responsibilities also aren’t defined, so it’s unclear who’s tackling each part. There’s no exploratory analysis or code documentation available yet, which limits feedback on analysis and clarity. (all of this was a requirement for this part of the project)

**Comment by mehulptech** [comment]
Hi @TanSA05 

Thank you for your feedback. Following up on that, we have now:
1) Merged and cleaned the dataset
2) Defined each team members
3) Completed exploratory analysis, documentation and other requirements as a part of this Team Project

We invite you to please review our project again after the completion of Part II and share your feedback.

Thanks,
Team 0
